[package]
name = "scribe"
version = "0.1.0"
authors = ["Robert Hurst <rhurst@e-xact.com>"]
description = "A simple logger for Rust projects"
license = "MIT"

[dependencies]
colored = "1.5"
chrono = "0.4"
